# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: weather-comparator-automation

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      home:
        description: 'location'
        required: false  
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Maven Package
      run: mvn -B clean package -DskipTests
    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | cut -f 3 -d ' ' | cut -d '.' -f 1) \
        && CHROMEDRIVER_RELEASE=$(curl --location --fail --retry 3 http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}) \
        && curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver_linux64.zip "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_RELEASE/chromedriver_linux64.zip" \
        && cd /tmp \
        && unzip chromedriver_linux64.zip \
        && rm -rf chromedriver_linux64.zip \
        && sudo mv chromedriver /usr/local/bin/chromedriver \
        && sudo chmod +x /usr/local/bin/chromedriver \
        && chromedriver --version
    - name: Maven Verify
      run: mvn test -Dtest=OpenWeatherAPITest#GetWeatherDetails test
